version: "3.0"

# Parallel processing workflow
# Multiple jobs run in parallel, then converge to a final job

jobs:
  # Initial job that starts the workflow
  prepare-environment:
    command: "echo"
    args: ["Preparing environment..."]

  # These three jobs run in parallel after prepare-environment completes
  process-region-us:
    command: "echo"
    args: ["Processing US region data..."]
    requires:
      - prepare-environment: "COMPLETED"

  process-region-eu:
    command: "echo"
    args: ["Processing EU region data..."]
    requires:
      - prepare-environment: "COMPLETED"

  process-region-asia:
    command: "echo"
    args: ["Processing ASIA region data..."]
    requires:
      - prepare-environment: "COMPLETED"

  # This job waits for all parallel jobs to complete
  aggregate-results:
    command: "echo"
    args: ["Aggregating results from all regions..."]
    requires:
      - process-region-us: "COMPLETED"
      - process-region-eu: "COMPLETED"
      - process-region-asia: "COMPLETED"

  # Final job
  generate-report:
    command: "echo"
    args: ["Generating final report..."]
    requires:
      - aggregate-results: "COMPLETED"
