version: 1
volumes:
  - data-pipeline

jobs:
  data-processing:
    runtime: python-3.11-ml
    command: python3
    args: [ "data-processor.py" ]
    uploads:
      files: [ "data-processor.py" ]
    volumes: [ "data-pipeline" ]
  
  data-analysis:
    runtime: python-3.11-ml
    command: python3
    args: [ "data-analyzer.py" ]
    uploads:
      files: [ "data-analyzer.py" ]
    volumes: [ "data-pipeline" ]
    requires:
      - data-processing: "COMPLETED"
  
  final-report:
    runtime: python-3.11-ml
    command: python3
    args: [ "-c", "import json; print('=== Final Report ==='); [print(f'📄 {f}: {json.load(open(f))}') for f in ['processed_data.json', 'analysis_results.json'] if __import__('os').path.exists(f)]; print('✅ Multi-job workflow completed successfully!')" ]
    volumes: [ "data-pipeline" ]
    requires:
      - data-analysis: "COMPLETED"