jobs:
  # Simple hello world job
  hello:
    command: "echo"
    args: [ "Hello, World!" ]
    runtime: "python-3.11-ml"
    resources:
      max_memory: 64

  # Python analytics job with uploads and volumes  
  analytics:
    command: "python3"
    args: [ "analyze.py" ]
    runtime: "python-3.11-ml"
    uploads:
      files: [ "analyze.py", "data.csv" ]
    volumes: [ "analytics-data" ]
    resources:
      max_memory: 512
      max_cpu: 75

  # Long-running server job
  webserver:
    command: "nginx"
    args: [ "-g", "daemon off;" ]
    runtime: "python-3.11-ml"
    volumes: [ "web-content" ]
    resources:
      max_memory: 128
      max_cpu: 25

  # Scheduled backup job
  backup:
    command: "bash"
    args: [ "-c", "tar -czf /volumes/backups/backup-$(date +%Y%m%d).tar.gz /data" ]
    runtime: "python-3.11-ml"
    volumes: [ "backups", "data" ]
    resources:
      max_memory: 512
      max_io_bps: 1048576