version: "3.0"

# ML pipeline workflow with actual ML scripts
jobs:
  data-validation:
    command: "python3"
    args: [ "prepare_data.py" ]
    runtime: "python-3.11-ml"
    uploads:
      files: [ "prepare_data.py" ]
    volumes: [ "ml-pipeline" ]

  feature-engineering:
    command: "python3"
    args: [ "select_features.py" ]
    runtime: "python-3.11-ml"
    uploads:
      files: [ "select_features.py" ]
    volumes: [ "ml-pipeline" ]
    requires:
      - data-validation: "COMPLETED"

  model-training:
    command: "python3"
    args: [ "train.py" ]
    runtime: "python-3.11-ml"
    uploads:
      files: [ "train.py" ]
    volumes: [ "ml-pipeline" ]
    requires:
      - feature-engineering: "COMPLETED"

  model-evaluation:
    command: "python3"
    args: [ "evaluate.py" ]
    runtime: "python-3.11-ml"
    uploads:
      files: [ "evaluate.py" ]
    volumes: [ "ml-pipeline" ]
    requires:
      - model-training: "COMPLETED"

  deployment:
    command: "python3"
    args: [ "test_model.py" ]
    runtime: "python-3.11-ml"
    uploads:
      files: [ "test_model.py" ]
    volumes: [ "ml-pipeline" ]
    requires:
      - model-evaluation: "COMPLETED"