version: "3.0"

# Corrected test for environment variables (using double quotes for substitution)
jobs:
  test-env-correct:
    command: "bash"
    args: [ "-c", "echo \"Environment test:\"; echo \"NODE_ENV=$NODE_ENV\"; echo \"SECRET_KEY exists: ${SECRET_KEY:+yes}\"; echo \"Both variables:\"; echo \"NODE_ENV=$NODE_ENV, SECRET_KEY=${SECRET_KEY:0:6}...\"" ]
    environment:
      NODE_ENV: "testing"
    secret_environment:
      SECRET_KEY: "secret-value-123"
    resources:
      max_memory: 128