version: "3.0"

# Invalid Environment Variable Test
# This workflow contains invalid environment variables that should fail validation

jobs:
  # Invalid environment variable names
  invalid-names:
    command: "bash"
    args: [ "-c", "echo 'This should fail'" ]
    environment:
      123INVALID: "starts-with-number"  # Invalid: starts with number
      "INVALID-VAR": "contains-hyphen"  # Invalid: contains hyphen
      "INVALID VAR": "contains-space"   # Invalid: contains space
      "INVALID.VAR": "contains-dot"     # Invalid: contains dot
    resources:
      max_memory: 128