version: "3.0"

# Secret vs Regular Environment Variables Demo
# Shows the difference between regular and secret environment variables

jobs:
  # Job with regular environment variables (visible in logs)
  public-config:
    command: "bash"
    args: [ "-c", "echo 'App Name: $APP_NAME'; echo 'Version: $APP_VERSION'; echo 'Environment: $NODE_ENV'; echo 'Port: $PORT'" ]
    environment:
      APP_NAME: "my-awesome-app"
      APP_VERSION: "1.0.0"
      NODE_ENV: "production"
      PORT: "8080"
    resources:
      max_memory: 128

  # Job with secret environment variables (hidden from logs)
  secret-config:
    command: "bash"
    args: [ "-c", "echo 'Database connected with password length:' ${#DB_PASSWORD}; echo 'API key prefix:' ${API_KEY:0:10}...; echo 'JWT secret configured:' ${JWT_SECRET:+yes}" ]
    secret_environment:
      DB_PASSWORD: "super-secret-db-password-12345"
      API_KEY: "dummy_api_key_for_testing_purposes_only"
      JWT_SECRET: "jwt-super-secret-signing-key-here"
    requires:
      - public-config: "COMPLETED"
    resources:
      max_memory: 128

  # Job with mixed environment variables
  mixed-config:
    command: "bash"
    args: [ "-c", "echo 'Service: $SERVICE_NAME on $NODE_ENV'; echo 'API endpoint configured:' ${API_ENDPOINT:+yes}; echo 'Secret token configured:' ${SECRET_TOKEN:+yes}" ]
    environment:
      SERVICE_NAME: "payment-service"
      NODE_ENV: "production"
      API_ENDPOINT: "https://api.company.com/v1"
    secret_environment:
      SECRET_TOKEN: "secret-service-token-abc123"
      ENCRYPTION_KEY: "32-char-encryption-key-for-data"
    requires:
      - secret-config: "COMPLETED"
    resources:
      max_memory: 128

  # Job that writes config file with mixed variables
  write-config:
    command: "bash"
    args: [ "-c", "echo 'service_name=$SERVICE_NAME' > /volumes/config/app.conf; echo 'environment=$NODE_ENV' >> /volumes/config/app.conf; echo 'api_endpoint=$API_ENDPOINT' >> /volumes/config/app.conf; echo 'Configuration written to file'; cat /volumes/config/app.conf" ]
    environment:
      SERVICE_NAME: "data-processor"
      NODE_ENV: "staging"
      API_ENDPOINT: "https://staging-api.company.com"
    secret_environment:
      DATABASE_URL: "postgresql://user:secret@db:5432/app"
    volumes: [ "config" ]
    requires:
      - mixed-config: "COMPLETED"
    resources:
      max_memory: 128

  # Job that demonstrates environment variable precedence
  test-precedence:
    command: "bash"
    args: [ "-c", "echo 'Final config:'; echo 'Service: $SERVICE_NAME'; echo 'Debug: $DEBUG_MODE'; echo 'Secret configured:' ${SECRET_KEY:+yes}" ]
    environment:
      SERVICE_NAME: "final-service"  # This will override any previous setting
      DEBUG_MODE: "false"
    secret_environment:
      SECRET_KEY: "final-secret-key-override"
    volumes: [ "config" ]
    requires:
      - write-config: "COMPLETED"
    resources:
      max_memory: 128