version: "3.0"

# Valid Environment Variable Test
# This workflow contains only valid environment variables

jobs:
  # Valid environment variables only
  valid-env:
    command: "bash"
    args: [ "-c", "echo 'Valid variables: $VALID_VAR, $ANOTHER_VAR, Secret exists: ${SECRET_VALID:+yes}'" ]
    environment:
      VALID_VAR: "this-is-valid"
      ANOTHER_VAR: "123_test"
      _UNDERSCORE_START: "valid"
    secret_environment:
      SECRET_VALID: "secret-value"
    resources:
      max_memory: 128