version: "3.0"

# Environment Variable Validation Test
# This workflow tests various validation scenarios

jobs:
  # Valid environment variables
  valid-env:
    command: "bash"
    args: [ "-c", "echo 'Valid variables: $VALID_VAR, $ANOTHER_VAR'" ]
    environment:
      VALID_VAR: "this-is-valid"
      ANOTHER_VAR: "123_test"
      _UNDERSCORE_START: "valid"
    secret_environment:
      SECRET_VALID: "secret-value"
    resources:
      max_memory: 128

  # Test for conflict detection (this should fail validation)
  conflict-test:
    command: "bash"
    args: [ "-c", "echo 'This should fail validation'" ]
    environment:
      CONFLICTED_VAR: "regular-value"
    secret_environment:
      CONFLICTED_VAR: "secret-value"  # Same key in both - should fail
    resources:
      max_memory: 128

  # Test reserved variable names (should warn but not fail)
  reserved-vars:
    command: "bash"
    args: [ "-c", "echo 'Testing reserved variables'" ]
    environment:
      PATH: "/custom/path"  # Reserved variable - should warn
      CUSTOM_VAR: "ok"
    resources:
      max_memory: 128